package com.fevziomurtekin.android_mvvm_architecture.Model

class userInfo (
    val login:String = "",
    val id:Int=0,
    val node_id:String = "",
    val gravatar_id:String = "",
    val avatar_url:String = "",
    val url:String = "",
    val followers_url:String = "",
    val following_url:String = "",
    val gists_url:String = "",
    val starred_url:String = "",
    val subscriptions_url:String = "",
    val organizations_url:String = "",
    val repos_url:String = "",
    val events_url:String = "",
    val received_events_url:String = "",
    val type:String = "",
    val site_admin:Boolean =false,
    val name:String = "",
    val company:String = "",
    val blog:String = "",
    val location:String = "",
    val email: String? = null,
    val hireable:Boolean = false,
    val bio:String = "",
    val public_repos:Int = 0,
    val public_gist:Int = 0,
    val followers:Int = 0,
    val following:Int = 0,
    val created_at:String = "",
    val updated_at:String = ""
)